name: Docker CI reusable

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1, Jul 20 2026

      - name: Test container
        run: |
          docker compose up -d
          sleep 40
          curl -f http://localhost:8090/actuator/health || exit 1
          docker compose down
